import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "http://localhost:8080" });

export type Client =
	paths["/api/rest/clients/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["clients_by_pk"];

export type Freelance =
	paths["/api/rest/freelances/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["freelances_by_pk"];

export type CreateTimesheet =
	paths["/api/rest/timesheets"]["post"]["requestBody"]["content"]["application/json"];
export type Timesheet =
	paths["/api/rest/timesheets/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["timesheets_by_pk"];
export type Timesheets =
	paths['/api/rest/timesheets']["get"]["responses"]["200"]["content"]["application/json"]["timesheets"];

export type TimesheetsByPeriod =
	paths['/api/rest/timesheets/period/{period}']["get"]["responses"]["200"]["content"]["application/json"]["timesheets"];

export type TimesheetByProjectTaskIdAndPeriod =
	paths['/api/rest/timesheets/project-task/{project_task_id}/period/{period}']['get']['responses']['200']['content']['application/json']['timesheets'];

export type UpdateTimesheetByPeriod =
	paths['/api/rest/timesheets/period/{period}']["put"]["requestBody"]["content"]["application/json"];

export type Project =
	paths["/api/rest/projects/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["projects_by_pk"];
export type Projects =
	paths['/api/rest/projects']["get"]["responses"]["200"]["content"]["application/json"]["projects"];
export type CreateProject =
	paths["/api/rest/projects"]["post"]["requestBody"]["content"]["application/json"];

export type ProjetTask =
	paths["/api/rest/projects_tasks/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["projects_tasks_by_pk"];
export type ProjectTasks =
	paths['/api/rest/projects_tasks']["get"]["responses"]["200"]["content"]["application/json"]["projects_tasks"];
