import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

export const client = createClient<paths>({ baseUrl: "http://0.0.0.0:8080" });

export type Project =
	paths["/api/rest/projects/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["projects_by_pk"];
export type Client =
	paths["/api/rest/clients/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["clients_by_pk"];
export type Freelance =
	paths["/api/rest/freelances/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["freelances_by_pk"];
export type Timesheet =
	paths["/api/rest/timesheets/{id}"]["get"]["responses"]["200"]["content"]["application/json"]["timesheets_by_pk"];
